### ISSUE TITLE
Timeline for local model support

### ISSUE THREAD

**Issue by vongomben** [bonastreyair/node-red-contrib-teachable-machine#12]
Planning to toy around with this node, and thanks for developing it. 

Is local processing on your roadmap?

![immagine](https://user-images.githubusercontent.com/1215847/81064628-4c292100-8eda-11ea-9784-2fc5ff594781.png)

**Comment by bonastreyair** [comment]
Yes! It is in the roadmap that's why I've added the option on the menu 😄.

I have a rough version but still not functional. Once I can make it totally work I will release it. I will leave the issue open just in case other has the same question as you until next release is out. This is my hobby so don't expect to be very soon, but it is in the works.

Hope you can enjoy and play a lot with the actual version!

Thanks!

**Comment by rozza-m** [comment]
Yes please, I'd also love this

**Comment by MarcooF** [comment]
I´m looking forward this feature!

**Comment by frizull** [comment]
Sounds like a great feature, would love to have the model run locally!

**Comment by bonastreyair** [comment]
After a long time I finally got some spare time to implement it! (I needed to move to tfjs-node to make it work...)

You can now use it locally without a required internet connection. 
Please check the latest `1.4.0` version.

@vongomben @rozza-m @MarcooF @frizull let me know if you encounter any issue. 
Thanks 🙏!
