### ISSUE TITLE
 Installation goes wrong about node-red-contrib-teachable-machine

### ISSUE THREAD

**Issue by lpj669** [bonastreyair/node-red-contrib-teachable-machine#73]
Hello everyone. After installing Node-red-contrib-teachable-machine in node-red, the ERR_DLOPEN_FAILED message appears, as shown in the figure. The program cannot be deployed.
How to solve this problem? I hopesomeone can help me, thanks!
![无标题1](https://user-images.githubusercontent.com/98530587/215936649-4eeb817f-8c02-4036-a660-d34cf416f799.jpg)
![无标题2](https://user-images.githubusercontent.com/98530587/215936674-ad7d1d5f-51f5-447c-9fb6-16750d05c5e3.jpg)

**Comment by egs2003** [comment]
nodered      | 20 Feb 12:40:14 - [info] Modul wird installiert: node-red-contrib-teachable-machine, Version: 1.4.0
nodered      | 20 Feb 12:41:41 - [info] Installiertes Modul: node-red-contrib-teachable-machine
nodered      | 20 Feb 12:41:42 - [info] Hinzugefügte Node-Typen:
nodered      | 20 Feb 12:41:42 - [info]  - node-red-contrib-teachable-machine:teachable machine : Error: Cannot find module '/data/node_modules/semver/index.js'. Please verify that the package.json has a valid "main" entry

![grafik](https://user-images.githubusercontent.com/8488313/220097104-0ce764b7-bb89-4bdf-95d8-7bd2748f036f.png)

**Comment by bonastreyair** [comment]
if it is docker that you are using, it is not compatible since its base image is Alpine. You can use the latests 3.1 version from dev with Debian base image and it works! https://hub.docker.com/layers/nodered/node-red-dev/v3.1.0-beta.4-debian/images/sha256-82a1b46a1fbc5c1ff49bccb23380988fa289d64e3a8eaf4baf71ebaefd858579?context=explore

check https://github.com/node-red/node-red-docker/issues/378
