### ISSUE TITLE
Trouble installing, either from palette or cmd 

### ISSUE THREAD

**Issue by kccrkccr** [bonastreyair/node-red-contrib-teachable-machine#76]
Whether I install from the palette or command window, I get the same error: Error: The specified module could not be found. \\?\C:\Users\katel\.node-red\node_modules\@tensorflow\tfjs-node\lib\napi-v5\tfjs_binding.node (line:6)  
I can see that module where it should be (unless I've made a mistake) so I'm not sure what's going on. Thanks for your time and I apologize if I'm missing something obvious.

**Comment by kccrkccr** [comment]
I tried installation on a different Windows PC and got the same error.

**Comment by kccrkccr** [comment]
I tried it on another computer running windows and got the same error

**Comment by kccrkccr** [comment]
I uninstalled and reinstalled node-red and now get the same error as the other poster: ERR_DLOPEN_FAILED in the palette manager. In the CMD window I get continue to get a similar error to before, "- node-red-contrib-teachable-machine:teachable machine : Error: The specified module could not be found.
\\?\C:\Users\katel\.node-red\node_modules\@tensorflow\tfjs-node\lib\napi-v5\tfjs_binding.node"

**Comment by elyancorrea** [comment]
+1

It's related to alpine image from docker and tensorflow.js

**Comment by bonastreyair** [comment]
exactly! it will be automatically fixed with 3.1 version using Debian base image

https://github.com/node-red/node-red-docker/issues/378

closing the issue, you can try it with the dev version, since it works! https://hub.docker.com/layers/nodered/node-red-dev/v3.1.0-beta.4-debian/images/sha256-82a1b46a1fbc5c1ff49bccb23380988fa289d64e3a8eaf4baf71ebaefd858579?context=explore
